# Site settings
title: Leonsux
SEOTitle: Leonsux Blog
header-img: img/post-bg-desk.jpg
email: gooleonsux@gmail.com
description: "Every failure is leading towards success."
keyword: "leonsux, leon, bolg, 博客, 前端, HTML, JavaScript, JS, Git, Github, Vue, React"
url: "https://leonsux.github.io/"
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/leonsux/leonsux.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Try Everything"
sidebar-avatar: /img/me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
zhihu_username:     sun-zy-84/activities
github_username:    leonsux
facebook_username:  
jianshu_username:   2a0b2825ab82
#twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: Monokai
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
disqus_username: leonsux

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 7426f6dc6861afa0d410   #生成的clientID
  clientSecret: 9b2bda64861621e4b00ea7e851c88c7d0793ee73  #同上
  repo: leonsux.github.io    #仓库名称
  owner: leonsux    #github用户名
  admin: leonsux
  distractionFreeMode: true #是否启用类似FB的阴影遮罩




# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-107712729-2'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "简书",
        href: "http://www.jianshu.com/u/2a0b2825ab82"
    },{
        title: "github",
        href: "https://github.com/leonsux"
    },{
        title: "segmentfault",
        href: "https://segmentfault.com/u/xiansui"
    }, {
        title: "掘金",
        href: "https://juejin.cn/user/905653311247688"
    }
]
